name: touch-ex
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pytorch-gpu
  - torchvision
  - scikit-learn
  - transformers
  - timm
  - numpy
  - pandas
  - matplotlib
  - plotly
  - seaborn
  - datasets>=2.19
  - pyarrow>=15
  - huggingface_hub
  - pillow
  - ipykernel
  - ipywidgets
